name = "phanerotes"
version = "0.1.0"
license = "license"
author = "John Stewart"
maintainer = "cane.cubo@gmail.com"
copyright = "Copyright 2026, John Stewart"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = ["blas"]

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib="*"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.5.0"

[[test]]
name = "tester"
source-dir = "test"
main = "main.f90"

